services:
 db:
  container_name: postgres_container
  image: postgres:16.9
  ports:
    - 5000:5432
  environment:
    POSTGRES_DB: db
    POSTGRES_USER: db_user
    POSTGRES_PASSWORD: db_pass
  volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql

  af:
    container_name: airflow_container
    image: apache/airflow:3.0.2
    ports:
      - 8000:8080
    envirinment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgesql+psycopg2://airflow:airflow@db:5432/airflow_db
    volume:
      - ./airflow/dag:/opt/airflow/dags
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge