services:
 db:
  container_name: postgres_container
  image: postgres:16.9
  ports:
    - 5000:5432
  environment:
    POSTGRES_DB: db
    POSTGRES_USER: db_user
    POSTGRES_PASSWORD: db_pass
  volumes:
    - ./postgres/data:/var/lib/postgresql/data
    - ./postgres/airflow_init.sql:/docker-entrypoint-initdb.d/airflow_init.sql
  networks:
    - my-network
  
    
 af:
  container_name: airflow_container
  image: apache/airflow:3.0.2
  ports:
    - 8000:8080
  environment:
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
  volumes: # portals to room #2 docker container from room #1 local machine
    - ./airflow/dags:/opt/airflow/dags #portal a
    - ./api_request:/opt/airflow/api_request # portal b
  depends_on:
    - db
  networks:
    - my-network
  command: >
    bash -c "airflow db migrate && airflow standalone"

 dbt:
  container_name: dbt
  image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
  volumes:
    - ./dbt/my_project:/usr/app
    - ./dbt:/root/.dbt
  working_dir: /usr/app
  environment:
    DBT_PROFILES_DIR: "/root/.dbt"
  depends_on:
    - db
  networks:
    - my-network
  command: run

  
networks:
  my-network:
    driver: bridge